version: "3.9"
services:
  app-name:
    build:
      context: .
    image: vaxoscopedashboard:1.0.0
    container_name: vaxoscopedashboard
    ports:
      - "5000:5000"
    environment:
      - TARGET=LIVE
    restart: unless-stopped